name: CI/CD
on:
  push:
    branches:
      - main
      - master
      - develop
      - 'releases/**'
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest
    steps:
        # actions/checkout@v3 извлекает репозиторий чтобы workflow мог получить к нему доступ
      - uses: actions/checkout@v3
        # actions/setup-java@v3 скачивает java, и позволяет настроить запуск проекта
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'
        # без этих 2 строк ниже будет ошибка ./gradlew: Permission denied
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
      - run: ./gradlew build --no-daemon
      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: src/main/java
        run: ./gradlew build sonar --info