# name: Название
name: CI
# on: На какой триггер будет реагировать чтобы запуститься
on:
  # workflow_dispatch: этот workflow будем запускать в ручном режиме
  workflow_dispatch:
# jobs: список job которые будут запущены
jobs:
  # build: имя job
  build:
    # runs-on: на какой машине (операционной системе надо запустить воркфлоу)
    runs-on: ubuntu-latest
    # steps: шаги
    steps:
      # - name: имя шага
      - name: Get repository code
        # run: запуск команды
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
        # uses: запуск actions из маркетплейса
        # actions/checkout@v3 извлекает репозиторий чтобы workflow мог получить к нему доступ
      - uses: actions/checkout@v3
        # actions/setup-java@v3 скачивает java, и позволяет настроить запуск проекта
      - uses: actions/setup-java@v3
        # with: запустить с следующими параметрами
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'
        # без этих 2 строк ниже будет ошибка ./gradlew: Permission denied
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
      - run: ./gradlew build --no-daemon
