name: CI/CD
on:
  push:
    branches:
      - main
      - master
      - develop
      - 'releases/**'
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  sonarqube:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
       fetch-depth: 0
    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@master
      with:
        projectBaseDir: app/src
        args: >
          -Dsonar.tests=tests/
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        SONAR_ROOT_CERT: ${{ secrets.SONAR_ROOT_CERT }}
        LC_ALL: "ru_RU.UTF-8"
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        # actions/checkout@v3 извлекает репозиторий чтобы workflow мог получить к нему доступ
        uses: actions/checkout@v3
        # actions/setup-java@v3 скачивает java, и позволяет настроить запуск проекта
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'
        # без этих 2 строк ниже будет ошибка ./gradlew: Permission denied
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
      - run: ./gradlew build --no-daemon